


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."course" (
    "id_courses" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "lecturer" "text" NOT NULL,
    "phone" "text",
    "day" "text" NOT NULL,
    "start" time without time zone NOT NULL,
    "end" time without time zone NOT NULL,
    "room" "text" NOT NULL,
    "sks" bigint NOT NULL,
    "link" "text",
    "alias" "text",
    "id_workspace" bigint NOT NULL
);


ALTER TABLE "public"."course" OWNER TO "postgres";


ALTER TABLE "public"."course" ALTER COLUMN "id_courses" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."otp" (
    "id_otp" bigint NOT NULL,
    "id_user" bigint NOT NULL,
    "otp_code" "text" NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "used_at" timestamp with time zone,
    "is_used" boolean DEFAULT false NOT NULL,
    "purpose" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."otp" OWNER TO "postgres";


ALTER TABLE "public"."otp" ALTER COLUMN "id_otp" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."otp_id_otp_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."presence" (
    "id_presence" bigint NOT NULL,
    "id_course" bigint NOT NULL,
    "presences_at" timestamp with time zone DEFAULT "now"(),
    "status" "text" NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_workspace" bigint NOT NULL
);


ALTER TABLE "public"."presence" OWNER TO "postgres";


ALTER TABLE "public"."presence" ALTER COLUMN "id_presence" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."presence_id_presence_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."task" (
    "id_task" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_course" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "deadline" timestamp with time zone NOT NULL,
    "priority" "text" NOT NULL,
    "status" "text" NOT NULL,
    "score" bigint,
    "link" "text",
    "id_workspace" bigint
);


ALTER TABLE "public"."task" OWNER TO "postgres";


ALTER TABLE "public"."task" ALTER COLUMN "id_task" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id_user" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" NOT NULL,
    "email" "text" NOT NULL,
    "password" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_verified" boolean DEFAULT false NOT NULL,
    "supabase_uid" "text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workspace" (
    "id_workspace" bigint NOT NULL,
    "id_user" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."workspace" OWNER TO "postgres";


ALTER TABLE "public"."workspace" ALTER COLUMN "id_workspace" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workspace_id_workspace_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."course"
    ADD CONSTRAINT "course_id_courses_key" UNIQUE ("id_courses");



ALTER TABLE ONLY "public"."course"
    ADD CONSTRAINT "course_pkey" PRIMARY KEY ("id_courses");



ALTER TABLE ONLY "public"."otp"
    ADD CONSTRAINT "otp_pkey" PRIMARY KEY ("id_otp");



ALTER TABLE ONLY "public"."presence"
    ADD CONSTRAINT "presence_id_presence_key" UNIQUE ("id_presence");



ALTER TABLE ONLY "public"."presence"
    ADD CONSTRAINT "presence_pkey" PRIMARY KEY ("id_presence");



ALTER TABLE ONLY "public"."task"
    ADD CONSTRAINT "task_id_task_key" UNIQUE ("id_task");



ALTER TABLE ONLY "public"."task"
    ADD CONSTRAINT "task_pkey" PRIMARY KEY ("id_task");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "user_id_user_key" UNIQUE ("id_user");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id_user");



ALTER TABLE ONLY "public"."workspace"
    ADD CONSTRAINT "workspace_id_workspace_key" UNIQUE ("id_workspace");



ALTER TABLE ONLY "public"."workspace"
    ADD CONSTRAINT "workspace_pkey" PRIMARY KEY ("id_workspace");



ALTER TABLE ONLY "public"."course"
    ADD CONSTRAINT "course_id_workspace_fkey" FOREIGN KEY ("id_workspace") REFERENCES "public"."workspace"("id_workspace");



ALTER TABLE ONLY "public"."otp"
    ADD CONSTRAINT "otp_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."users"("id_user") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."presence"
    ADD CONSTRAINT "presence_id_course_fkey" FOREIGN KEY ("id_course") REFERENCES "public"."course"("id_courses") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."presence"
    ADD CONSTRAINT "presence_id_workspace_fkey" FOREIGN KEY ("id_workspace") REFERENCES "public"."workspace"("id_workspace") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."task"
    ADD CONSTRAINT "task_id_course_fkey" FOREIGN KEY ("id_course") REFERENCES "public"."course"("id_courses") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workspace"
    ADD CONSTRAINT "workspace_id_workspace_fkey" FOREIGN KEY ("id_workspace") REFERENCES "public"."users"("id_user") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow read for all" ON "public"."presence" FOR SELECT USING (true);



ALTER TABLE "public"."course" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "maksa" ON "public"."course" FOR SELECT USING (true);



CREATE POLICY "maksa" ON "public"."task" FOR SELECT USING (true);



CREATE POLICY "maksa" ON "public"."users" USING (true) WITH CHECK (true);



CREATE POLICY "maksague" ON "public"."otp" USING (true) WITH CHECK (true);



CREATE POLICY "maksapakebanget" ON "public"."course" USING (true) WITH CHECK (true);



CREATE POLICY "maksapakebanget" ON "public"."presence" USING (true) WITH CHECK (true);



CREATE POLICY "maksapakebanget" ON "public"."task" USING (true) WITH CHECK (true);



ALTER TABLE "public"."otp" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."presence" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."task" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "terserahguelahbodoamat" ON "public"."workspace" USING (true) WITH CHECK (true);



ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."workspace" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."course" TO "anon";
GRANT ALL ON TABLE "public"."course" TO "authenticated";
GRANT ALL ON TABLE "public"."course" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."otp" TO "anon";
GRANT ALL ON TABLE "public"."otp" TO "authenticated";
GRANT ALL ON TABLE "public"."otp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."otp_id_otp_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."otp_id_otp_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."otp_id_otp_seq" TO "service_role";



GRANT ALL ON TABLE "public"."presence" TO "anon";
GRANT ALL ON TABLE "public"."presence" TO "authenticated";
GRANT ALL ON TABLE "public"."presence" TO "service_role";



GRANT ALL ON SEQUENCE "public"."presence_id_presence_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."presence_id_presence_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."presence_id_presence_seq" TO "service_role";



GRANT ALL ON TABLE "public"."task" TO "anon";
GRANT ALL ON TABLE "public"."task" TO "authenticated";
GRANT ALL ON TABLE "public"."task" TO "service_role";



GRANT ALL ON SEQUENCE "public"."task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."task_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_id_user_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workspace" TO "anon";
GRANT ALL ON TABLE "public"."workspace" TO "authenticated";
GRANT ALL ON TABLE "public"."workspace" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workspace_id_workspace_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workspace_id_workspace_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workspace_id_workspace_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































