export const navItemsSUm = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Calendar", href: "/calendar" },
];

export const navItemsMain = [
  { name: "My tasks", href: "/tasks" },
  { name: "Courses", href: "/courses" },
  { name: "Presences", href: "/presences" },
];

export const navItemsSide = [
  { name: "Back", href: "/workspaces" },
  { name: "Logout", href: "/logout" },
];

export const navLanding = [
  { name: "Why us", href: "/#whyus" },
  { name: "Features", href: "/#features" },
  { name: "Reviews", href: "/#review"}
];

export const navAuth = [
  { name: "Login", href: "/auth/login" },
  { name: "Register", href: "/auth/register" },
];

export const navUser = [
  { name: "Workspaces", href: "/workspaces" },
];

export const dataPresence = [
  {
    id: 1,
    date: "06/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:32:57",
    status: "Presence",
    note: "",
  },
  {
    id: 2,
    date: "06/10/2025",
    course: "Kecerdasan Artifisia",
    time: "18:28:17",
    status: "Presence",
    note: "",
  },
  {
    id: 3,
    date: "07/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "09:12:40",
    status: "Presence",
    note: "",
  },
  {
    id: 4,
    date: "08/10/2025",
    course: "Komputasi Awan dan Terdistribusi",
    time: "14:35:40",
    status: "Presence",
    note: "",
  },
  {
    id: 5,
    date: "09/10/2025",
    course: "Keamanan Siber",
    time: "10:25:34",
    status: "Presence",
    note: "",
  },
  {
    id: 6,
    date: "10/10/2025",
    course: "Tata Tulis Ilmiah",
    time: "09:45:56",
    status: "Absent",
    note: "Izin",
  },
  {
    id: 7,
    date: "10/10/2025",
    course: "Manajemen Proyek T",
    time: "15:25:12",
    status: "Absent",
    note: "Sakit",
  },
  {
    id: 8,
    date: "13/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:29:27",
    status: "Presence",
    note: "",
  },
  {
    id: 9,
    date: "13/10/2025",
    course: "Kecerdasan Artifisia",
    time: "17:58:17",
    status: "Presence",
    note: "",
  },
  {
    id: 10,
    date: "14/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "08:59:37",
    status: "Presence",
    note: "",
  },
  {
    id: 1,
    date: "06/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:32:57",
    status: "Presence",
    note: "",
  },
  {
    id: 2,
    date: "06/10/2025",
    course: "Kecerdasan Artifisia",
    time: "18:28:17",
    status: "Presence",
    note: "",
  },
  {
    id: 3,
    date: "07/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "09:12:40",
    status: "Presence",
    note: "",
  },
  {
    id: 4,
    date: "08/10/2025",
    course: "Komputasi Awan dan Terdistribusi",
    time: "14:35:40",
    status: "Presence",
    note: "",
  },
  {
    id: 5,
    date: "09/10/2025",
    course: "Keamanan Siber",
    time: "10:25:34",
    status: "Presence",
    note: "",
  },
  {
    id: 6,
    date: "10/10/2025",
    course: "Tata Tulis Ilmiah",
    time: "09:45:56",
    status: "Absent",
    note: "Izin",
  },
  {
    id: 7,
    date: "10/10/2025",
    course: "Manajemen Proyek T",
    time: "15:25:12",
    status: "Absent",
    note: "Sakit",
  },
  {
    id: 8,
    date: "13/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:29:27",
    status: "Presence",
    note: "",
  },
  {
    id: 9,
    date: "13/10/2025",
    course: "Kecerdasan Artifisia",
    time: "17:58:17",
    status: "Presence",
    note: "",
  },
  {
    id: 10,
    date: "14/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "08:59:37",
    status: "Presence",
    note: "",
  },
  {
    id: 1,
    date: "06/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:32:57",
    status: "Presence",
    note: "",
  },
  {
    id: 2,
    date: "06/10/2025",
    course: "Kecerdasan Artifisia",
    time: "18:28:17",
    status: "Presence",
    note: "",
  },
  {
    id: 3,
    date: "07/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "09:12:40",
    status: "Presence",
    note: "",
  },
  {
    id: 4,
    date: "08/10/2025",
    course: "Komputasi Awan dan Terdistribusi",
    time: "14:35:40",
    status: "Presence",
    note: "",
  },
  {
    id: 5,
    date: "09/10/2025",
    course: "Keamanan Siber",
    time: "10:25:34",
    status: "Presence",
    note: "",
  },
  {
    id: 6,
    date: "10/10/2025",
    course: "Tata Tulis Ilmiah",
    time: "09:45:56",
    status: "Absent",
    note: "Izin",
  },
  {
    id: 7,
    date: "10/10/2025",
    course: "Manajemen Proyek T",
    time: "15:25:12",
    status: "Absent",
    note: "Sakit",
  },
  {
    id: 8,
    date: "13/10/2025",
    course: "Sosio Informatik dan Keprofesian",
    time: "15:29:27",
    status: "Presence",
    note: "",
  },
  {
    id: 9,
    date: "13/10/2025",
    course: "Kecerdasan Artifisia",
    time: "17:58:17",
    status: "Presence",
    note: "",
  },
  {
    id: 10,
    date: "14/10/2025",
    course: "Implementasi Pengujian Perangkat Lunak",
    time: "08:59:37",
    status: "Presence",
    note: "",
  },
];
